/**
 * Category: STRINGS
 * Tags: maps anagrams
 *
 * Given a string S and a smaller string T, check if an anagram of T exists in S.
 */
import { assert } from "console";

class Solver {
  text: string;
  charChecker: Map<string, number>;

  constructor(s: string) {
    this.text = s;
  }

  hasAnagramSubstring(pattern: string): boolean {
    if (pattern.length === 0) return false; // <-- This might not be the correct way to handle empty patterns
    if (pattern === this.text) return true;

    const patternCounts = new Map<string, number>();
    const windowCounts = new Map<string, number>();
    for (let i = 0; i < pattern.length; i++) {
      const pChar = pattern[i];

      if (!patternCounts.has(pChar)) patternCounts.set(pChar, 0);
      patternCounts.set(pChar, patternCounts.get(pChar) + 1);

      const tChar = this.text[i];
      if (!windowCounts.has(tChar)) windowCounts.set(tChar, 0);
      windowCounts.set(tChar, windowCounts.get(tChar) + 1);
    }

    // console.log(patternCounts);
    for (let i = pattern.length; i < this.text.length; i++) {
      if (this.isComplete(patternCounts, windowCounts)) return true;

      const newChar = this.text[i];
      const firstChar = this.text[i - pattern.length];
      if (!windowCounts.has(newChar)) windowCounts.set(newChar, 0);
      windowCounts.set(newChar, windowCounts.get(newChar) + 1);
      windowCounts.set(firstChar, windowCounts.get(firstChar) - 1);
    }

    return this.isComplete(patternCounts, windowCounts);
  }

  isComplete(
    pCounts: Map<string, number>,
    windowCounts: Map<string, number>
  ): boolean {
    // console.log(windowCounts);

    for (const pair of Array.from(pCounts.entries())) {
      const char = pair[0];
      const count = pair[1];
      if (count !== windowCounts.get(char)) return false;
    }

    return true;
  }
}

const solver = new Solver("asasfasasdfaa");
assert(solver.hasAnagramSubstring("sad"));
assert(solver.hasAnagramSubstring("saf"));
assert(!solver.hasAnagramSubstring("sass"));
assert(solver.hasAnagramSubstring("f"));
assert(solver.hasAnagramSubstring("ssaaafsadsaaf"));
assert(solver.hasAnagramSubstring("afa"));
assert(solver.hasAnagramSubstring("sasfas"));

const fastTester = new Solver(
  `aksdfhkjasdfhkjawhegashduerurofdspvdmkvdmvjdshdfsuewjewbhqwhsdfhkjawhegashduerurofdspvdmkvdmvjdshdfsuewjewbsdfhkjawhegashduerurofdspvdmkvdmvjdshdfsuewjewbsdfhkjawhegashduerurofdspvdmkvdmvjdshdfsuewjewbsdfhkjawhegashduerurofdspvdmkvdmvjdshdfsuewjewbsdfhkjawhegashdusdfalksjdflkadsjfklahjkheghahskjdhgjhasndkbaspdfasdfhkjawhegashduerurofdasdlkfhaksjdfhkahsdkhaskjdvkjaskdkrhkasiefhahsdjkfjasjdfhhashdfkakjshdfhkaweogasdgfpasoieuaiowhfkajskdfspvdmkvdmvjdshdfsuewjewbsdfhkjawhegashduerurofdspvdmkvdmvjdshdfsuewjewberurofdspsdfhkjawhegashduerurofdspvdmkvdmvjdshdfsuewjewbvdmkvdmsdfhkjawhegashduerurofdspvdmkvdmvjdshdfsuewjewbvjdshdfsuewjewbsdfhkjawhegashduerurofdspvdmkvdmvjdshdfsuewjewbsdfhkjawhegashduerurofdspvdmkvdmvjdshdfsuewjewbfweiufhkajfakjsfaksdfhkjasdfhkjawhegashduerurofdspvdmkvdmvjdshdfsuewjewbhqwhsdfhkjawhegashduerurofdspvdmkvdmvjdshdfsuewjewbsdfhkjawhegashduerurofdspvdmkvdmvjdshdfsuewjewbsdfhkjawhegashduerurofdspvdmkvdmvjdshdfsuewjewbsdfhkjawhegashduerurofdspvdmkvdmvjdshdfsuewjewbsdfhkjawhegashdusdfalksjdflkadsjfklahjkheghahskjdhgjhasndkbaspdfasdfhkjawhegashduerurofdasdlkfhaksjdfhkahsdkhaskjdvkjaskdkrhkasiefhahsdjkfjasjdfhhashdfkakjshdfhkaweogasdgfpasoieuaiowhfkajskdfspvdmkvdmvjdshdfsuewjewbsdfhkjawhegashduerurofdspvdmkvdmvjdshdfsuewjewberurofdspsdfhkjawhegashduerurofdspvdmkvdmvjdshdfsuewjewbvdmkvdmsdfhkjawhegashduerurofdspvdmkvdmvjdshdfsuewjewbvjdshdfsuewjewbsdfhkjawhegashduerurofdspvdmkvdmvjdshdfsuewjewbsdfhkjawhegashduerurofdspvdmkvdmvjdshdfsuewjewbfweiufhkajfakjsfaksdfhkjasdfhkjawhegashduerurofdspvdmkvdmvjdshdfsuewjewbhqwhsdfhkjawhegashduerurofdspvdmkvdmvjdshdfsuewjewbsdfhkjawhegashduerurofdspvdmkvdmvjdshdfsuewjewbsdfhkjawhegashduerurofdspvdmkvdmvjdshdfsuewjewbsdfhkjawhegashduerurofdspvdmkvdmvjdshdfsuewjewbsdfhkjawhegashdusdfalksjdflkadsjfklahjkheghahskjdhgjhasndkbaspdfasdfhkjawhegashduerurofdasdlkfhaksjdfhkahsdkhaskjdvkjaskdkrhkasiefhahsdjkfjasjdfhhashdfkakjshdfhkaweogasdgfpasoieuaiowhfkajskdfspvdmkvdmvjdshdfsuewjewbsdfhkjawhegashduerurofdspvdmkvdmvjdshdfsuewjewberurofdspsdfhkjawhegashduerurofdspvdmkvdmvjdshdfsuewjewbvdmkvdmsdfhkjawhegashduerurofdspvdmkvdmvjdshdfsuewjewbvjdshdfsuewjewbsdfhkjawhegashduerurofdspvdmkvdmvjdshdfsuewjewbsdfhkjawhegashduerurofdspvdmkvdmvjdshdfsuewjewbfweiufhkajfakjsfaksdfhkjasdfhkjawhegashduerurofdspvdmkvdmvjdshdfsuewjewbhqwhsdfhkjawhegashduerurofdspvdmkvdmvjdshdfsuewjewbsdfhkjawhegashduerurofdspvdmkvdmvjdshdfsuewjewbsdfhkjawhegashduerurofdspvdmkvdmvjdshdfsuewjewbsdfhkjawhegashduerurofdspvdmkvdmvjdshdfsuewjewbsdfhkjawhegashdusdfalksjdflkadsjfklahjkheghahskjdhgjhasndkbaspdfasdfhkjawhegashduerurofdasdlkfhaksjdfhkahsdkhaskjdvkjaskdkrhkasiefhahsdjkfjasjdfhhashdfkakjshdfhkaweogasdgfpasoieuaiowhfkajskdfspvdmkvdmvjdshdfsuewjewbsdfhkjawhegashduerurofdspvdmkvdmvjdshdfsuewjewberurofdspsdfhkjawhegashduerurofdspvdmkvdmvjdshdfsuewjewbvdmkvdmsdfhkjawhegashduerurofdspvdmkvdmvjdshdfsuewjewbvjdshdfsuewjewbsdfhkjawhegashduerurofdspvdmkvdmvjdshdfsuewjewbsdfhkjawhegashduerurofdspvdmkvdmvjdshdfsuewjewbfweiufhkajfakjsfaksdfhkjasdfhkjawhegashduerurofdspvdmkvdmvjdshdfsuewjewbhqwhsdfhkjawhegashduerurofdspvdmkvdmvjdshdfsuewjewbsdfhkjawhegashduerurofdspvdmkvdmvjdshdfsuewjewbsdfhkjawhegashduerurofdspvdmkvdmvjdshdfsuewjewbsdfhkjawhegashduerurofdspvdmkvdmvjdshdfsuewjewbsdfhkjawhegashdusdfalksjdflkadsjfklahjkheghahskjdhgjhasndkbaspdfasdfhkjawhegashduerurofdasdlkfhaksjdfhkahsdkhaskjdvkjaskdkrhkasiefhahsdjkfjasjdfhhashdfkakjshdfhkaweogasdgfpasoieuaiowhfkajskdfspvdmkvdmvjdshdfsuewjewbsdfhkjawhegashduerurofdspvdmkvdmvjdshdfsuewjewberurofdspsdfhkjawhegashduerurofdspvdmkvdmvjdshdfsuewjewbvdmkvdmsdfhkjawhegashduerurofdspvdmkvdmvjdshdfsuewjewbvjdshdfsuewjewbsdfhkjawhegashduerurofdspvdmkvdmvjdshdfsuewjewbsdfhkjawhegashduerurofdspvdmkvdmvjdshdfsuewjewbfweiufhkajfakjsfaksdfhkjasdfhkjawhegashduerurofdspvdmkvdmvjdshdfsuewjewbhqwhsdfhkjawhegashduerurofdspvdmkvdmvjdshdfsuewjewbsdfhkjawhegashduerurofdspvdmkvdmvjdshdfsuewjewbsdfhkjawhegashduerurofdspvdmkvdmvjdshdfsuewjewbsdfhkjawhegashduerurofdspvdmkvdmvjdshdfsuewjewbsdfhkjawhegashdusdfalksjdflkadsjfklahjkheghahskjdhgjhasndkbaspdfasdfhkjawhegashduerurofdasdlkfhaksjdfhkahsdkhaskjdvkjaskdkrhkasiefhahsdjkfjasjdfhhashdfkakjshdfhkaweogasdgfpasoieuaiowhfkajskdfspvdmkvdmvjdshdfsuewjewbsdfhkjawhegashduerurofdspvdmkvdmvjdshdfsuewjewberurofdspsdfhkjawhegashduerurofdspvdmkvdmvjdshdfsuewjewbvdmkvdmsdfhkjawhegashduerurofdspvdmkvdmvjdshdfsuewjewbvjdshdfsuewjewbsdfhkjawhegashduerurofdspvdmkvdmvjdshdfsuewjewbsdfhkjawhegashduerurofdspvdmkvdmvjdshdfsuewjewbfweiufhkajfakjsfaksdfhkjasdfhkjawhegashduerurofdspvdmkvdmvjdshdfsuewjewbhqwhsdfhkjawhegashduerurofdspvdmkvdmvjdshdfsuewjewbsdfhkjawhegashduerurofdspvdmkvdmvjdshdfsuewjewbsdfhkjawhegashduerurofdspvdmkvdmvjdshdfsuewjewbsdfhkjawhegashduerurofdspvdmkvdmvjdshdfsuewjewbsdfhkjawhegashdusdfalksjdflkadsjfklahjkheghahskjdhgjhasndkbaspdfasdfhkjawhegashduerurofdasdlkfhaksjdfhkahsdkhaskjdvkjaskdkrhkasiefhahsdjkfjasjdfhhashdfkakjshdfhkaweogasdgfpasoieuaiowhfkajskdfspvdmkvdmvjdshdfsuewjewbsdfhkjawhegashduerurofdspvdmkvdmvjdshdfsuewjewberurofdspsdfhkjawhegashduerurofdspvdmkvdmvjdshdfsuewjewbvdmkvdmsdfhkjawhegashduerurofdspvdmkvdmvjdshdfsuewjewbvjdshdfsuewjewbsdfhkjawhegashduerurofdspvdmkvdmvjdshdfsuewjewbsdfhkjawhegashduerurofdspvdmkvdmvjdshdfsuewjewbfweiufhkajfakjsfaksdfhkjasdfhkjawhegashduerurofdspvdmkvdmvjdshdfsuewjewbhqwhsdfhkjawhegashduerurofdspvdmkvdmvjdshdfsuewjewbsdfhkjawhegashduerurofdspvdmkvdmvjdshdfsuewjewbsdfhkjawhegashduerurofdspvdmkvdmvjdshdfsuewjewbsdfhkjawhegashduerurofdspvdmkvdmvjdshdfsuewjewbsdfhkjawhegashdusdfalksjdflkadsjfklahjkheghahskjdhgjhasndkbaspdfasdfhkjawhegashduerurofdasdlkfhaksjdfhkahsdkhaskjdvkjaskdkrhkasiefhahsdjkfjasjdfhhashdfkakjshdfhkaweogasdgfpasoieuaiowhfkajskdfspvdmkvdmvjdshdfsuewjewbsdfhkjawhegashduerurofdspvdmkvdmvjdshdfsuewjewberurofdspsdfhkjawhegashduerurofdspvdmkvdmvjdshdfsuewjewbvdmkvdmsdfhkjawhegashduerurofdspvdmkvdmvjdshdfsuewjewbvjdshdfsuewjewbsdfhkjawhegashduerurofdspvdmkvdmvjdshdfsuewjewbsdfhkjawhegashduerurofdspvdmkvdmvjdshdfsuewjewbfweiufhkajfakjsfaksdfhkjasdfhkjawhegashduerurofdspvdmkvdmvjdshdfsuewjewbhqwhsdfhkjawhegashduerurofdspvdmkvdmvjdshdfsuewjewbsdfhkjawhegashduerurofdspvdmkvdmvjdshdfsuewjewbsdfhkjawhegashduerurofdspvdmkvdmvjdshdfsuewjewbsdfhkjawhegashduerurofdspvdmkvdmvjdshdfsuewjewbsdfhkjawhegashdusdfalksjdflkadsjfklahjkheghahskjdhgjhasndkbaspdfasdfhkjawhegashduerurofdasdlkfhaksjdfhkahsdkhaskjdvkjaskdkrhkasiefhahsdjkfjasjdfhhashdfkakjshdfhkaweogasdgfpasoieuaiowhfkajskdfspvdmkvdmvjdshdfsuewjewbsdfhkjawhegashduerurofdspvdmkvdmvjdshdfsuewjewberurofdspsdfhkjawhegashduerurofdspvdmkvdmvjdshdfsuewjewbvdmkvdmsdfhkjawhegashduerurofdspvdmkvdmvjdshdfsuewjewbvjdshdfsuewjewbsdfhkjawhegashduerurofdspvdmkvdmvjdshdfsuewjewbsdfhkjawhegashduerurofdspvdmkvdmvjdshdfsuewjewbfweiufhkajfakjsfaksdfhkjasdfhkjawhegashduerurofdspvdmkvdmvjdshdfsuewjewbhqwhsdfhkjawhegashduerurofdspvdmkvdmvjdshdfsuewjewbsdfhkjawhegashduerurofdspvdmkvdmvjdshdfsuewjewbsdfhkjawhegashduerurofdspvdmkvdmvjdshdfsuewjewbsdfhkjawhegashduerurofdspvdmkvdmvjdshdfsuewjewbsdfhkjawhegashdusdfalksjdflkadsjfklahjkheghahskjdhgjhasndkbaspdfasdfhkjawhegashduerurofdasdlkfhaksjdfhkahsdkhaskjdvkjaskdkrhkasiefhahsdjkfjasjdfhhashdfkakjshdfhkaweogasdgfpasoieuaiowhfkajskdfspvdmkvdmvjdshdfsuewjewbsdfhkjawhegashduerurofdspvdmkvdmvjdshdfsuewjewberurofdspsdfhkjawhegashduerurofdspvdmkvdmvjdshdfsuewjewbvdmkvdmsdfhkjawhegashduerurofdspvdmkvdmvjdshdfsuewjewbvjdshdfsuewjewbsdfhkjawhegashduerurofdspvdmkvdmvjdshdfsuewjewbsdfhkjawhegashduerurofdspvdmkvdmvjdshdfsuewjewbfweiufhkajfakjsfaksdfhkjasdfhkjawhegashduerurofdspvdmkvdmvjdshdfsuewjewbhqwhsdfhkjawhegashduerurofdspvdmkvdmvjdshdfsuewjewbsdfhkjawhegashduerurofdspvdmkvdmvjdshdfsuewjewbsdfhkjawhegashduerurofdspvdmkvdmvjdshdfsuewjewbsdfhkjawhegashduerurofdspvdmkvdmvjdshdfsuewjewbsdfhkjawhegashdusdfalksjdflkadsjfklahjkheghahskjdhgjhasndkbaspdfasdfhkjawhegashduerurofdasdlkfhaksjdfhkahsdkhaskjdvkjaskdkrhkasiefhahsdjkfjasjdfhhashdfkakjshdfhkaweogasdgfpasoieuaiowhfkajskdfspvdmkvdmvjdshdfsuewjewbsdfhkjawhegashduerurofdspvdmkvdmvjdshdfsuewjewberurofdspsdfhkjawhegashduerurofdspvdmkvdmvjdshdfsuewjewbvdmkvdmsdfhkjawhegashduerurofdspvdmkvdmvjdshdfsuewjewbvjdshdfsuewjewbsdfhkjawhegashduerurofdspvdmkvdmvjdshdfsuewjewbsdfhkjawhegashduerurofdspvdmkvdmvjdshdfsuewjewbfweiufhkajfakjsfaksdfhkjasdfhkjawhegashduerurofdspvdmkvdmvjdshdfsuewjewbhqwhsdfhkjawhegashduerurofdspvdmkvdmvjdshdfsuewjewbsdfhkjawhegashduerurofdspvdmkvdmvjdshdfsuewjewbsdfhkjawhegashduerurofdspvdmkvdmvjdshdfsuewjewbsdfhkjawhegashduerurofdspvdmkvdmvjdshdfsuewjewbsdfhkjawhegashdusdfalksjdflkadsjfklahjkheghahskjdhgjhasndkbaspdfasdfhkjawhegashduerurofdasdlkfhaksjdfhkahsdkhaskjdvkjaskdkrhkasiefhahsdjkfjasjdfhhashdfkakjshdfhkaweogasdgfpasoieuaiowhfkajskdfspvdmkvdmvjdshdfsuewjewbsdfhkjawhegashduerurofdspvdmkvdmvjdshdfsuewjewberurofdspsdfhkjawhegashduerurofdspvdmkvdmvjdshdfsuewjewbvdmkvdmsdfhkjawhegashduerurofdspvdmkvdmvjdshdfsuewjewbvjdshdfsuewjewbsdfhkjawhegashduerurofdspvdmkvdmvjdshdfsuewjewbsdfhkjawhegashduerurofdspvdmkvdmvjdshdfsuewjewbfweiufhkajfakjsfaksdfhkjasdfhkjawhegashduerurofdspvdmkvdmvjdshdfsuewjewbhqwhsdfhkjawhegashduerurofdspvdmkvdmvjdshdfsuewjewbsdfhkjawhegashduerurofdspvdmkvdmvjdshdfsuewjewbsdfhkjawhegashduerurofdspvdmkvdmvjdshdfsuewjewbsdfhkjawhegashduerurofdspvdmkvdmvjdshdfsuewjewbsdfhkjawhegashdusdfalksjdflkadsjfklahjkheghahskjdhgjhasndkbaspdfasdfhkjawhegashduerurofdasdlkfhaksjdfhkahsdkhaskjdvkjaskdkrhkasiefhahsdjkfjasjdfhhashdfkakjshdfhkaweogasdgfpasoieuaiowhfkajskdfspvdmkvdmvjdshdfsuewjewbsdfhkjawhegashduerurofdspvdmkvdmvjdshdfsuewjewberurofdspsdfhkjawhegashduerurofdspvdmkvdmvjdshdfsuewjewbvdmkvdmsdfhkjawhegashduerurofdspvdmkvdmvjdshdfsuewjewbvjdshdfsuewjewbsdfhkjawhegashduerurofdspvdmkvdmvjdshdfsuewjewbsdfhkjawhegashduerurofdspvdmkvdmvjdshdfsuewjewbfweiufhkajfakjsfaksdfhkjasdfhkjawhegashduerurofdspvdmkvdmvjdshdfsuewjewbhqwhsdfhkjawhegashduerurofdspvdmkvdmvjdshdfsuewjewbsdfhkjawhegashduerurofdspvdmkvdmvjdshdfsuewjewbsdfhkjawhegashduerurofdspvdmkvdmvjdshdfsuewjewbsdfhkjawhegashduerurofdspvdmkvdmvjdshdfsuewjewbsdfhkjawhegashdusdfalksjdflkadsjfklahjkheghahskjdhgjhasndkbaspdfasdfhkjawhegashduerurofdasdlkfhaksjdfhkahsdkhaskjdvkjaskdkrhkasiefhahsdjkfjasjdfhhashdfkakjshdfhkaweogasdgfpasoieuaiowhfkajskdfspvdmkvdmvjdshdfsuewjewbsdfhkjawhegashduerurofdspvdmkvdmvjdshdfsuewjewberurofdspsdfhkjawhegashduerurofdspvdmkvdmvjdshdfsuewjewbvdmkvdmsdfhkjawhegashduerurofdspvdmkvdmvjdshdfsuewjewbvjdshdfsuewjewbsdfhkjawhegashduerurofdspvdmkvdmvjdshdfsuewjewbsdfhkjawhegashduerurofdspvdmkvdmvjdshdfsuewjewbfweiufhkajfakjsfaksdfhkjasdfhkjawhegashduerurofdspvdmkvdmvjdshdfsuewjewbhqwhsdfhkjawhegashduerurofdspvdmkvdmvjdshdfsuewjewbsdfhkjawhegashduerurofdspvdmkvdmvjdshdfsuewjewbsdfhkjawhegashduerurofdspvdmkvdmvjdshdfsuewjewbsdfhkjawhegashduerurofdspvdmkvdmvjdshdfsuewjewbsdfhkjawhegashdusdfalksjdflkadsjfklahjkheghahskjdhgjhasndkbaspdfasdfhkjawhegashduerurofdasdlkfhaksjdfhkahsdkhaskjdvkjaskdkrhkasiefhahsdjkfjasjdfhhashdfkakjshdfhkaweogasdgfpasoieuaiowhfkajskdfspvdmkvdmvjdshdfsuewjewbsdfhkjawhegashduerurofdspvdmkvdmvjdshdfsuewjewberurofdspsdfhkjawhegashduerurofdspvdmkvdmvjdshdfsuewjewbvdmkvdmsdfhkjawhegashduerurofdspvdmkvdmvjdshdfsuewjewbvjdshdfsuewjewbsdfhkjawhegashduerurofdspvdmkvdmvjdshdfsuewjewbsdfhkjawhegashduerurofdspvdmkvdmvjdshdfsuewjewbfweiufhkajfakjsfaksdfhkjasdfhkjawhegashduerurofdspvdmkvdmvjdshdfsuewjewbhqwhsdfhkjawhegashduerurofdspvdmkvdmvjdshdfsuewjewbsdfhkjawhegashduerurofdspvdmkvdmvjdshdfsuewjewbsdfhkjawhegashduerurofdspvdmkvdmvjdshdfsuewjewbsdfhkjawhegashduerurofdspvdmkvdmvjdshdfsuewjewbsdfhkjawhegashdusdfalksjdflkadsjfklahjkheghahskjdhgjhasndkbaspdfasdfhkjawhegashduerurofdasdlkfhaksjdfhkahsdkhaskjdvkjaskdkrhkasiefhahsdjkfjasjdfhhashdfkakjshdfhkaweogasdgfpasoieuaiowhfkajskdfspvdmkvdmvjdshdfsuewjewbsdfhkjawhegashduerurofdspvdmkvdmvjdshdfsuewjewberurofdspsdfhkjawhegashduerurofdspvdmkvdmvjdshdfsuewjewbvdmkvdmsdfhkjawhegashduerurofdspvdmkvdmvjdshdfsuewjewbvjdshdfsuewjewbsdfhkjawhegashduerurofdspvdmkvdmvjdshdfsuewjewbsdfhkjawhegashduerurofdspvdmkvdmvjdshdfsuewjewbfweiufhkajfakjsf`
);
assert(!fastTester.hasAnagramSubstring("wwei"));
assert(fastTester.hasAnagramSubstring("asd"));
assert(
  fastTester.hasAnagramSubstring(
    "dfsuewjewberurofdspsdfhkjawhegashduerurofdspvdmkvdmvjdshdfsuewjewbvdmkvdmsdfhkjawhegashduerurofdspvdmkvdmvjdshdfsuewjewbvjdshdfsuewjewbsdfhkjawhegashduerurofdspvdmkvdmvjdshdfsuewjewbsdfhkjawhegashduerurofdspvdmkvd"
  )
);

console.log("All assertions passed.");
